#dependencies:
#  - Here would go dependencies or some such?
testdata:
   - PUBMED_SINGLEFILE
rundata:
   - PUBMED
build:
   - bash build.sh
test:
   - bash run.sh -i PUBMED_SINGLEFILE -o OUTPUTFILE
run:
   - bash run.sh -i PUBMED -o OUTPUTFILE
output:
   - OUTPUTFILE
